// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhO-Qku3xEfKUGaFiwc9mcdliXbsk7rgU',
    appId: '1:980914699767:web:ca09736483f63b5386c2f2',
    messagingSenderId: '980914699767',
    projectId: 'tracker-hajj',
    authDomain: 'tracker-hajj.firebaseapp.com',
    storageBucket: 'tracker-hajj.firebasestorage.app',
    measurementId: 'G-QSSKCD1ZL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmn0FP_V_e5Ifs1VvQjMA_tTIZdoAqKdk',
    appId: '1:980914699767:android:49efd6b6f4b3136886c2f2',
    messagingSenderId: '980914699767',
    projectId: 'tracker-hajj',
    storageBucket: 'tracker-hajj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOyff0ppb3rBbOiWkSWUJb7vEWDPU8B9k',
    appId: '1:980914699767:ios:1225a168a14a978986c2f2',
    messagingSenderId: '980914699767',
    projectId: 'tracker-hajj',
    storageBucket: 'tracker-hajj.firebasestorage.app',
    iosBundleId: 'com.example.trackingLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOyff0ppb3rBbOiWkSWUJb7vEWDPU8B9k',
    appId: '1:980914699767:ios:1225a168a14a978986c2f2',
    messagingSenderId: '980914699767',
    projectId: 'tracker-hajj',
    storageBucket: 'tracker-hajj.firebasestorage.app',
    iosBundleId: 'com.example.trackingLocation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhO-Qku3xEfKUGaFiwc9mcdliXbsk7rgU',
    appId: '1:980914699767:web:72f42f1bd6e6957586c2f2',
    messagingSenderId: '980914699767',
    projectId: 'tracker-hajj',
    authDomain: 'tracker-hajj.firebaseapp.com',
    storageBucket: 'tracker-hajj.firebasestorage.app',
    measurementId: 'G-LNHWJ0EB7E',
  );

}